-- BOOK DATA

--[[La mise en forme des données du livre a l'air putain de bizarre. Donc voici le fichier de confinement pour ça.
Aucune indentation ne peut être utilisée sinon ça a l'air foutu dans la vue du livre.]]

Book_Shagalax_Page1 = [[<font face='Acadian Runes' color='#dbdbdb' size='4'><b>La Succession du Trône d'Écorce</b></font>
<font face='Acadian Runes' color='#dbdbdb'>Voici, écoutez maintenant le récit de l'ascension du Clan Ghorst vers le siège du Trône d'Écorce, tel que raconté par la vision de la voyante. Lorsque le monde était jeune, et que la Famille était encore inconnue de notre peuple, la force seule régnait en maître—des bâtons aiguisés, des pierres lancées par des mains calleuses, et des massues de bois lourd étaient les outils de la bataille. La victoire appartient à ceux qui possèdent la force brute et rien de plus. Mais ensuite, lorsque le Grand Arbre fut planté et que les Druides de la Lame marchèrent pour la première fois parmi nous, les vents du changement balayèrent la terre.

Les Druides, gardiens des racines sacrées, portaient des dons des dieux eux-mêmes : des lames d'acier étincelantes, tranchantes comme les vents des montagnes et brillantes comme les étoiles. Notre peuple, frappé d'émerveillement, tenait ces épées pour des reliques divines, les maniant dans des batailles glorieuses. Pourtant, nul n'osait questionner leur fabrication, à l'exception des audacieux et méprisés Shagalaxiens.</font>]]

Book_Shagalax_Page2 = [[<font face='Acadian Runes' color='#dbdbdb' size='4'><b>Le Savoir qui Engendra l'Hérésie</b></font>
<font face='Acadian Runes' color='#dbdbdb'>Après l'ascension des Druides de la Lame vers la Terre des Aïeux, pour les clans de l'époque, les Shagalaxiens n'étaient que des lâches, indignes de l'honneur sanglant des guerriers. Là où d'autres laissaient leurs lames se rouiller et se ruiner, les Shagalaxiens se détournèrent de la bataille, consumés par une obsession unique : découvrir comment fabriquer une telle arme. Ils ne virent pas de dons divins dans les épées des Druides, mais la preuve du feu de forge. Pour leurs questionnements, ils furent bannis, moqués et méprisés.

Pourtant, guidés par les murmures du Jeune Fils, les Shagalaxiens ne se découragèrent pas. On dit que dans les cendres des os d'un Druide de la Lame, ils eurent une vision : Toute chose peut être reforgée. Cette révélation les mena vers les pics gelés des Terres du Nord, vers le feu au cœur de la montagne — la Première Forge, plus ancienne que le temps lui-même. Là, ils découvrirent le secret de l'acier, le pliant à leur volonté, refaçonnant leur destin et celui de notre peuple.</font>]]

Book_Shagalax_Page3 = [[<font face='Acadian Runes' color='#dbdbdb' size='4'><b>L'Essor de l'Acier et le Premier Royaume Gorique</b></font>
<font face='Acadian Runes' color='#dbdbdb'>Lorsque les Shagalaxiens revinrent, les clans étaient brisés, leurs épées divines émoussées contre leurs cousins et leur foi vacillante. Les Shagalaxiens arrivèrent non en lâches mais en conquérants, revêtus d'armures inflexibles et maniant un acier plus tranchant et plus mortel que tout ce qui avait été vu auparavant. Ils taillèrent une voie sanglante vers le Trône d'Écorce, s'en emparant non par faveur divine mais par la maîtrise de la forge.

Sous leur règne, le Premier Royaume Gorique naquit, et la foi de la Famille fut restaurée. Leurs forges rugirent, refaçonnant les dépouilles de la guerre en machines de mort : des bêtes crachant de la vapeur, des dragons de fer et des armures impénétrables. Même le puissant Clan Ghorst ploya le genou, et les Shagalaxiens régnèrent sans contestation, seigneurs d'un Âge de Puissance.</font>]]

Book_Shagalax_Page4 = [[<font face='Acadian Runes' color='#dbdbdb' size='4'><b>Naissance de l'Hérésie</b></font>
<font face='Acadian Runes' color='#dbdbdb'>Mais les graines de la chute furent semées. Dans la guerre avant les ténèbres, le Grand Arbre fut mis à feu par le lâche Maximus, serviteur de la Seconde Famille. Le chaos balaya la terre, et les Shagalaxiens, si dépendants de leurs machines, furent laissés brisés. Wrathalax le Fou, le dernier roi de Shagalax, se tourna vers le blasphème dans son désespoir.

Tordant les paroles du Jeune Fils, il chercha le salut non dans la forge mais dans les restes brisés de ses machines, la ferraille rouillée. De ces carcasses brisées, il forgea le Dieu Machine — un être de fer grinçant et de pouvoir impie. Ses disciples, les Hérauts du Dieu Machine, peinèrent en secret, construisant leurs monstruosités hérétiques faites de cadavres de machines dans les profondeurs ombragées de Forgehome, la forteresse shagalaxienne.

Dans leur foyer hérétique, ils construisirent l'ultime souillure des dieux, le Broyeur. La relique qui servirait de vaisseau au Dieu Machine.</font>]]

Book_Shagalax_Page5 = [[<font face='Acadian Runes' color='#dbdbdb' size='4'><b>Le Siège de Forgehome</b></font>
<font face='Acadian Runes' color='#dbdbdb'>Les voyants avaient prédit le désastre : une montagne de fer qui dévorerait les restes du Grand Arbre dans une gueule broyeuse et noierait le monde sous une mer de scories en fusion. En cette heure sombre, Magthar Ghorsthand, chef du Clan Ghorst, appela les clans à s'unir. Même les fidèles Shagalaxiens, ceux qui avaient rejeté les enseignements de Wrathalax, relevèrent le défi.

Les clans unis assiégèrent Forgehome, une ville de smog étouffant et d'acier déchiqueté. Le sang coula à flots, mais la sagesse des Shagalaxiens rachetés renversa le cours de la bataille contre les monstruosités de ferraille, car ils en connaissaient les faiblesses. Wrathalax, désormais fusion de chair et de fer, affronta Magthar dans le sanctuaire du Broyeur. Leur duel ébranla la terre elle-même, mais ce fut Magthar qui porta le coup final, séparant Wrathalax de sa machine hérétique et mettant fin à son règne de terreur. Forgehome fut réduite en cendres, et avec elle, le Broyeur.</font>]]

Book_Shagalax_Page6 = [[<font face='Acadian Runes' color='#dbdbdb' size='4'><b>Rédemption et Échos de la Ferraille</b></font>
<font face='Acadian Runes' color='#dbdbdb'>Les loyaux Shagalaxiens furent honorés, leur place parmi les clans restaurée. Ils devinrent des symboles de rédemption, mais ceux qui s'accrochèrent au blasphème du Dieu Machine partirent en exil avant que leur hérésie ne soit découverte. Dans les étendues stériles, ces exilés bâtirent une ville de ferraille, une sinistre forteresse de rouille et de feu, où ils peinent encore à ressusciter leur faux dieu. Leurs cris hantés résonnent comme une moquerie de leurs origines sous la forme de leur chant impie :</font>
<font face='Acadian Runes' color='#dbdbdb' size='12'><b><i>"SHA-GA-LAX !"</i></b></font>]]

Book_Shagalax_Page7 = [[<font face='Acadian Runes' color='#dbdbdb' size='4'><b>L'Ère de Ghorst</b></font>
<font face='Acadian Runes' color='#dbdbdb'>Sous le règne du Clan Ghorst, les clans prospérèrent, unis sous le Trône d'Écorce. Pourtant, l'ombre de la guerre persiste, un sinistre rappel que l'hérésie contre la Famille doit être détruite. La forge ne refroidit jamais, et l'acier se souvient.

Ainsi se termine ce chapitre de notre saga, mais le récit n'est pas encore achevé. Car dans les ténèbres, la Machine attend, son destin de fer reforgé, sa haine toujours ardente.</font>]]

Book_Gore_Page1 = [[<font face='Acadian Runes' color='#dbdbdb' size='4'><b>Le Roi Faucheur</b></font>
<font face='Acadian Runes' color='#dbdbdb'>Aux jours de feu, quand la terre tremblait sous les Engendrés, le Clan Gore s'éleva à la domination. Du Père, la force et la fureur furent transmises, et de sa volonté, le Clan Gore naquit. Mais ce récit ne commence pas dans les salles de la grandeur—il commence avec un garçon rejeté, né de la honte d'un chef de guerre.

Le Clan Ghorst, autrefois le clan régnant et prétendant au titre d'enfants du Père, détenait le pouvoir sur la terre. Le puissant chef de guerre de Ghorst était un homme fier, trop fier, car il engendra un fils bâtard—un héritier auquel il ne pouvait prétendre. Dans son arrogance, il abandonna le garçon à la nature sauvage, le laissant être déchiré par les loups. Il ignorait que les loups ne dévoreraient pas le garçon, mais l'élèveraient comme l'un des leurs. Ils lui enseignèrent les voies de la nature, les lois du sang et de la griffe, et le pouvoir de la chasse.

Le garçon n'était pas un simple louveteau. Il devint féroce, plus fort qu'aucun homme, son cœur forgé dans les ténèbres des terres sauvages. Il combattit des ours à mains nues, déchirant leurs épaisses peaux avec ses dents et ses griffes. Nulle bête n'était trop forte, nul défi trop grand. Le garçon apprit à traquer le pays, ses sens aiguisés comme ceux d'un loup. Il ne fit plus qu'un avec la forêt, son corps aussi fort que la pierre, sa faim insatiable.</font>]]

Book_Gore_Page2 = [[<font face='Acadian Runes' color='#dbdbdb' size='4'><b>Épiphanie de la Trahison</b></font>
<font face='Acadian Runes' color='#dbdbdb'>Dans le silence de la nuit, le garçon—devenu un homme—observait de loin. Il voyait les bannières du Clan Ghorst flotter au vent, et depuis l'ombre, il contemplait les salles où son père régnait. Son cœur brûlait de questions. Qui était-il ? Pourquoi son père l'avait-il rejeté ? La vérité sur sa lignée lui était cachée, voilée par des années de silence et d'amertume.

Mais il observa jusqu'au jour où il connut la vérité. Son père avait été le chef de guerre du Clan Ghorst, celui qui l'avait jeté dans les terres sauvages comme s'il n'était rien. Son père, le puissant chef de guerre de Ghorst, le pourvoyeur des Clans, avait abandonné sa propre chair et son sang.

Pendant des années, les hommes du Clan Ghorst chuchotaient leur mépris pour leur chef. Ils le traitaient de lâche, d'imbécile, car le cœur de leurs dirigeants à travers les générations s'était amolli depuis la chute des Shagalaxiens. Ils parlaient de son orgueil et de sa honte, de l'enfant bâtard qu'il avait abandonné. Pourtant, nul n'osait le défier, car il était le plus grand guerrier à avoir jamais foulé ces terres. Sa force était sans égale, sa férocité sans pareille. Aucun homme ne pouvait lui tenir tête—pas même dans son état affaibli.

Mais le garçon, désormais un homme, n'était pas comme les autres. Il avait appris les voies des loups et le langage de la chasse. Il avait appris à attendre, à prendre son temps. Et quand l'heure fut venue, il se déplaça avec la rapidité d'un javelot, son cœur empli du feu de la vengeance.</font>]]

Book_Gore_Page3 = [[<font face='Acadian Runes' color='#dbdbdb' size='4'><b>L'Assaut du Roi Faucheur sur la Grande Salle</b></font>
<font face='Acadian Runes' color='#dbdbdb'>Le Roi Faucheur Kalkaslash, comme il se nommait désormais, fit irruption dans la longue salle du Clan Ghorst jusqu'au cœur du Trône d'Écorce. Avec des griffes acérées et les yeux brûlant de rage, il prit ce qui lui revenait de droit. Il déchira sans effort les guerriers du Clan Ghorst, chaque coup témoignant de ses années d'entraînement dans les terres sauvages. Finalement, il trouva son père, l'autrefois puissant chef de guerre. Sans hésitation, Kalkaslash déchiqueta son père de ses griffes, tranchant la chair et les os comme une lame dans du beurre. Les salles du Clan Ghorst furent teintes du rouge du sang du traître.

Ainsi, le chef de guerre de Ghorst tomba, et avec lui, le clan. Kalkaslash monta sur le trône, les salles du Clan Ghorst faisant désormais écho à son nom. Son ascension fut rapide, son pouvoir indéniable. Les guerriers de Ghorst s'agenouillèrent devant lui. Leurs cœurs emplis à la fois de peur et de crainte révérencielle alors qu'ils juraient fidélité au Roi Faucheur. Et à partir de ce jour, ils prirent le nom de Gore, car ils étaient désormais siens, liés par le sang et la volonté du Père.</font>]]

Book_Gore_Page4 = [[<font face='Acadian Runes' color='#dbdbdb' size='4'><b>Naissance du Clan de la Couronne</b></font>
<font face='Acadian Runes' color='#dbdbdb'>Le Clan Gore, le Clan de la Couronne, est né des cendres de la trahison et de la vengeance. L'armée de Kalkaslash, plus forte et plus féroce que toute autre, a balayé la terre, forçant tous les autres clans à s'incliner devant lui. Nul ne pouvait résister à la puissance du Roi Faucheur, dont les griffes et la force avaient déchiré les fondements mêmes du Clan Ghorst.
La volonté du Père fut accomplie. Tant que le sang de Kalkaslash bouillonnait de fureur, personne n'oserait le défier. Le Roi Faucheur avait pris sa place, et son nom serait gravé dans la pierre, dans le sang, et dans le cœur de tous ceux qui redoutaient son règne.

Voici le récit de l'ascension du Clan Gore, de l'enfant élevé par les loups, et du Roi Faucheur Kalkaslash, dont la force apporterait la ruine à tous ceux qui oseraient lui résister. Puisse son nom perdurer.</font>]]

Book_Druids_Page1 = [[<font face='Acadian Runes' color='#dbdbdb' size='4'><b>Arrivée des Druides de la Lame</b></font>
<font face='Acadian Runes' color='#dbdbdb'>L'histoire des Druides de la Lame est connue de tous les Gors, bien que la vérité en soit enfouie sous le givre et le sang, dispersée dans les vents du temps. On dit qu'ils sont venus à nous aux jours les plus sombres, lorsque nos terres gisaient brisées et que les esprits des morts hurlaient dans la nuit froide. Les Terres du Nord, autrefois un lieu de puissance, avaient été brisées lors des Anciennes Guerres. Ce qui restait de notre peuple errait dans les Terres Mortes comme des loups affamés, se battant pour des miettes, sans but.

Puis les Druides apparurent. Personne ne sait d'où ils venaient. Certains disent qu'ils étaient des messagers de la Famille, les cinq dieux qui façonnèrent le monde et le surveillent encore. D'autres croient qu'ils étaient les vestiges d'un âge oublié, ou des errants attirés par le Grand Arbre. Ce que nous savons, c'est ceci : ils portaient des lames comme nous n'en avions jamais vues, du métal forgé à partir des os des dieux eux-mêmes, assez tranchant pour couper le vent. Ils parlaient peu, mais leur présence suffisait à faire taire même le chef le plus assoiffé de sang.

Les Druides n'exigèrent pas d'allégeance—ils menèrent. À travers les étendues gelées, ils guidèrent nos tribus dispersées, à travers les blizzards et les forêts mortes, jusqu'à ce que nous arrivions au lieu des miracles : le Grand Arbre. Il se dressait haut comme une montagne, ses racines plongeaient profondément dans la croûte terrestre, ses branches s'étendaient larges comme les cieux. Mais surtout, autour de lui, la terre était vivante. Le givre n'avait pas tué la terre, l'air était chaud et le sol fertile. Les animaux vivaient en paix, l'eau était pure et coulait sans cesse, et les anciens temples des Druides se dressaient fièrement. C'est là, à l'ombre de cet arbre sacré, que les Druides parlèrent de la Famille.</font>]]

Book_Druids_Page2 = [[<font face='Acadian Runes' color='#dbdbdb' size='4'><b>La Famille</b></font>
<font face='Acadian Runes' color='#dbdbdb'>La Famille—cinq dieux, à la fois cruels et bienveillants, qui règnent sur la vie, la mort et le Pays des Aïeux où parviennent les dignes. Les Druides disaient que nous avions oublié la Famille, que nous leur avions tourné le dos, et que c'était la raison pour laquelle les Terres du Nord avaient été consumées par la mort. Mais ils disaient aussi qu'il y avait de l'espoir. Sous le Grand Arbre, nous pourrions retrouver la rédemption et la faveur des dieux.

Pourtant, nous, les Gores, ne sommes pas un peuple qui se contente de paroles. Nous voulions des réponses—des preuves. Nous voulions entendre les dieux parler, sentir leur pouvoir. Et ainsi, les Druides devinrent les réceptacles de leur puissance. Nous les traînâmes jusqu'aux racines du Grand Arbre et les déposâmes en offrande aux dieux. Leur sang s'écoula dans la terre, et l'Arbre frémit sous la puissance de leur sacrifice.
On dit que les dieux répondirent. Le ciel s'assombrit, et une vision vint à tous ceux qui se tenaient sous l'Arbre. Elle leur conféra les horreurs des Anciennes Guerres—la trahison, le massacre, la chute des Terres du Nord. Ils virent les seigneurs de l'Empire de la Lumière, gras et gloutons, assis sur des trônes d'or volé. Et ils se virent eux-mêmes, les Gores, s'élevant des cendres, brisant les couronnes de l'Empire, et répandant leur sang comme de l'hydromel lors d'un festin. C'était une promesse de vengeance et de gloire.

Au début, la vision ne nous unit pas—elle nous divisa. Certains crurent que les dieux appelaient à la guerre, à marcher vers le sud et à détruire l'Empire. D'autres affirmèrent que la vision était un avertissement, un rappel de ce qui arrive quand l'orgueil aveugle un peuple. Les tribus se querellèrent, puis se battirent, et davantage de sang fut versé sous l'Arbre.</font>]]

Book_Druids_Page3 = [[<font face='Acadian Runes' color='#dbdbdb' size='4'><b>Le Premier Royaume</b></font>
<font face='Acadian Runes' color='#dbdbdb'>Pourtant, du chaos, un Clan s'éleva au-dessus des autres, unit les tribus, forgea le premier Royaume, et prêta serment à la Famille : l'Empire de la Lumière paierait ses péchés dans le sang.

Les Druides ont disparu depuis longtemps, leurs corps nourrissant les racines du Grand Arbre. Leurs lames rouillent dans la neige, leur dessein accompli. Mais leur héritage perdure, dans les chants de guerre des Gores et les cicatrices que nous portons au cœur. Certains disent que les Druides savaient qu'ils mourraient, que leur sacrifice était la volonté des dieux.

Quelle que soit la vérité, une chose est certaine : les dieux exigent du sang, et nous, les Gores, sommes trop heureux d'en offrir. Que l'Empire tremble. Le Nord se souvient, et nous ne pardonnons pas.</font>]]

Book_Crast_Page1 = [[<font face='Acadian Runes' color='#dbdbdb' size='4'><b>Le Premier Voyant Aveugle</b></font>
<font face='Acadian Runes' color='#dbdbdb'>Le premier fut Aloris, né sous le signe de La Mère, du clan qu'on appelle les Crast. Nous sommes les déchus, les indésirables, ceux qui furent un jour précipités des falaises pour mourir sur les rochers en contrebas. Pourtant, grâce à une vie épargnée et un destin tissé dans les racines du Grand Arbre, nous avons survécu, notre nom désormais murmuré avec révérence parmi les Clans.

Dans les jours qui suivirent les Druides de la Lame, les enfants nés sous La Mère étaient considérés comme des faibles, des fardeaux inaptes au cycle impitoyable de la survie. La Mère, déesse de la vie et de la mort, était respectée, mais ses enfants étaient jugés indignes. Alors que les adeptes des autres membres de la Famille devenaient de puissants guerriers, ceux de La Mère étaient jetés des hautes falaises, leurs corps rendus à la terre pour nourrir le sol.

Mais notre histoire commence par une exception — un seul instant où la Famille choisit un chemin différent.</font>]]

Book_Crast_Page2 = [[<font face='Acadian Runes' color='#dbdbdb' size='4'><b>Le Crast Qui Fut Épargné</b></font>
<font face='Acadian Runes' color='#dbdbdb'>Aloris devait mourir, comme tant d'autres avant lui. Aveugle de naissance, son frêle corps fut tenu au-dessus des falaises tandis que les anciens psalmodiaient les rites ancestraux. Mais quelque chose arrêta la main de celui qui le tenait. Peut-être fut-ce la pitié, ou peut-être le vent porta-t-il la voix de la Mère ce jour-là. Quelle qu'en soit la cause, il ne fut pas jeté. À la place, il fut laissé dans la forêt, abandonné mais vivant.

La forêt devint son berceau, ses créatures sa famille. Les corbeaux révélèrent des secrets, et il entendit leur sagesse. Seul, il grandit, sa cécité n'étant pas un obstacle alors que le monde autour de lui parlait de façons que les autres ne pouvaient entendre. Il commença à voir sans yeux, à savoir sans connaître, à percevoir les fils du destin alors qu'ils se tissaient à travers les arbres et les cieux.

Un soir, alors qu'Aloris se reposait sous les branches d'un chêne ancien, partageant des secrets avec les corbeaux alentour, il eut une vision—une lame dans l'obscurité, son tranchant destiné au roi assis sur le Trône d'Écorce. Sans hésitation, il se rendit à la grande salle, un enfant frêle et crasseux entrant dans le monde de Gore.</font>]]

Book_Crast_Page3 = [[<font face='Acadian Runes' color='#dbdbdb' size='4'><b>La Clémence du Roi</b></font>
<font face='Acadian Runes' color='#dbdbdb'>Les autres l'auraient abattu, mais le roi, intrigué par son intrusion, ordonna qu'on s'arrête. <i>« Parle, »</i> commanda le roi, et ainsi fit-il. Il lui raconta l'assassin au sang noir qui attendait dans l'ombre, avec le visage d'un homme Goréen mais l'honneur d'un tueur ; une dague destinée à son cœur. Sceptique mais intrigué, le roi fit fouiller le village par ses hommes, et c'est là qu'ils trouvèrent le meurtrier en puissance, exactement comme Aloris l'avait prédit.

Pour lui avoir épargné la vie, le roi épargna Aloris, et celui-ci raconta au roi son origine — comment il était l'un des enfants de La Mère, laissé pour mort mais sauvé par hasard. Ému par son récit, le roi décréta un changement : désormais, tous les enfants nés sous La Mère ne seraient plus précipités des falaises. À la place, un sur dix serait épargné, leur vie étant un hommage aux dons de La Mère.

Ainsi naquirent les Crasts — non pas comme des guerriers ou des souverains, mais comme quelque chose de totalement différent.</font>]]

Book_Crast_Page4 = [[<font face='Acadian Runes' color='#dbdbdb' size='4'><b>Les Voyants de la Forêt</b></font>
<font face='Acadian Runes' color='#dbdbdb'>Le Clan Crast, bien que peu nombreux, commença à croître en nombre. Ceux d'entre nous épargnés par la mort portaient souvent d'étranges marques de la faveur de la Mère. Certains étaient défigurés, d'autres naissaient avec des talents particuliers. Beaucoup d'entre nous, comme moi-même, furent dotés de la Vision, capables de voir les chemins du destin se dérouler là où les autres ne voyaient que ténèbres.

<font face='Acadian Runes' color='#dbdbdb' size='4'><b>Le Tournant</b></font>
Malgré cela, la méfiance persistait. Ce n'est que des années plus tard, lorsque nous prévîmes les dragons des seigneurs ventrus fondre sur le Grand Arbre, que les Crasts furent véritablement acceptés. Personne ne nous crut. Les guerriers se moquèrent de nos visions, nous traitant de reliques d'un passé insensé. Mais lorsque les dragons arrivèrent, comme nous l'avions annoncé, et que leurs flammes marquèrent l'arbre sacré, ils ne purent plus douter.

La terre se fendit, le ciel se brisa, et la mer hurla depuis les restes calcinés du Grand Arbre, déversant les Engendrés. À partir de ce jour, les Clans révérèrent les Crasts. Bien qu'ils gardaient encore leurs distances, ils comprirent désormais que les enfants de la Mère, aussi étranges et fragiles que nous puissions paraître, étaient essentiels à leur survie.</font>]]

Book_Crast_Page5 = [[<font face='Acadian Runes' color='#dbdbdb' size='4'><b>L'Avenir des Crasts</b></font>
<font face='Acadian Runes' color='#dbdbdb'>Dans le sillage de la destruction du Grand Arbre et de la chute des grandes armées shagalaxiennes sous le règne du Roi Fou, ce furent les Crasts qui révélèrent la trahison au sein des Clans — ceux qui s'étaient alliés aux Hérauts du Dieu Machine. Ces traîtres cherchaient à offrir les restes du Grand Arbre en tribut, permettant aux Hérauts d'accomplir leur prophétie : une montagne de fer descendant pour dévorer l'Arbre dans une mâchoire broyeuse, noyant la terre sous une coulée de scories en fusion. Guidés par nos visions, nous avons arrêté cette catastrophe avant qu'elle ne commence, démasquant les conspirateurs et dispersant les Hérauts.

À présent, tandis que je raconte cette histoire, les Crasts se préparent à notre plus grand défi. Le Grand Arbre, blessé, commence à dépérir. Ses racines faiblissent, et la terre en souffre avec lui. Nous, les Crasts, avons pour mission de guider les Clans afin de restaurer la puissance de l'Arbre. Les guerriers et les souverains, autrefois si prompts à nous rejeter, se tiennent désormais à nos côtés, attendant nos directives.

Les enfants de la Mère étaient autrefois perçus comme faibles, mais nous leur avons montré la vérité : la force ne réside pas seulement dans les muscles ou l'acier, mais dans la sagesse, la prévoyance et la compréhension des cycles de la vie et de la mort.

Nous sommes les Crasts, les déchus qui se sont relevés. Et à travers nous, la volonté de la Mère perdure.</font>]]

Book_Harald_Page1 = [[<font face='Acadian Runes' color='#dbdbdb' size='4'><b>Le Léviathan</b></font>
<font face='Acadian Runes' color='#dbdbdb'>Les mers n'ont pas toujours été les nôtres. Pendant des années, elles furent dominées par les Vaisseaux de la Mort, des navires de fer et de flamme, manœuvrés par les seigneurs obèses qui revendiquaient les vagues comme leur saint domaine. Ces navires balayaient les océans de toute opposition, leur puissance témoignant de l'empire oppressif. Les Clans Goriques, liés à la terre, menèrent des guerres acharnées contre leur tyrannie, aiguisant notre force pour le jour où nous briserions leurs crânes.</font>

<font face='Acadian Runes' color='#dbdbdb' size='4'><b>Destruction des Vaisseaux de la Mort : L'Exploration du Clan Harald</b></font>
<font face='Acadian Runes' color='#dbdbdb'>Ce jour arriva lorsque les Vaisseaux de la Mort furent réduits à néant, leur armada brisée par la fureur du clan Harald. Leur flotte réduite en cendres et leur domination anéantie, les mers redevinrent silencieuses. Ce fut alors que le Clan Harald s'éleva pour réclamer ce qui nous avait été si longtemps refusé.

Les Haraldiens, comme toujours, virent la mer non comme une barrière mais comme une voie. Ils construisirent les premiers langskips, élancés et rapides, conçus pour danser sur les vagues et les porter vers l'inconnu. Le Loup-de-Mer, leur premier navire d'exploration, devint le symbole de leur esprit audacieux. C'était plus qu'un navire — c'était une promesse au Vieux Fils, l'ancien dieu des mers, que les Haraldiens honoreraient les eaux par leur courage et leur savoir-faire.

Avec le temps, leurs voyages les menèrent plus loin que quiconque n'aurait pu l'imaginer. Ils découvrirent de nouveaux rivages, transportèrent les richesses de l'Est vers les Clans, et devinrent l'avant-garde de l'exploration. Pourtant, ce fut lors d'un tel périple, à bord du langskip Hurle-Tempête, qu'ils affrontèrent leur plus grande épreuve.</font>]]

Book_Harald_Page2 = [[<font face='Acadian Runes' color='#dbdbdb' size='4'><b>Le Voyage du Hurle-Tempête</b></font>
<font face='Acadian Runes' color='#dbdbdb'>Le Hurle-Tempête navigua vers le nord, au-delà des fjords et des vents glacés, jusqu'à la lisière du monde où la mer est censée se perdre dans les ténèbres. Leur objectif était la Fosse Abyssale, un lieu murmuré dans les vieilles histoires, où la présence du Vieux Fils est la plus forte. Le voyage fut périlleux, mais les Haralders ne se laissèrent pas décourager.

C'est là, à la frontière du monde connu, que la tempête frappa. Les vagues s'élevaient plus haut que le mât, et les vents hurlaient avec une fureur qui semblait vivante. La foudre déchira le Pays des Aïeux, et le Hurle-Tempête fut ballotté comme un jouet. L'équipage lutta vaillamment, mais la colère de la tempête était trop grande.

Alors que la tempête atteignait son paroxysme, la mer elle-même sembla se fendre, et des profondeurs, Il émergea. Ce n'était ni une bête sans pensée ni un nouveau dieu, mais le Vieux Fils lui-même, sa forme immense s'élevant à la rencontre de ses fidèles. Sa peau avait la couleur de la tempête, et ses yeux étaient profonds et pleins de sagesse, comme s'ils portaient le poids des secrets de l'océan. Des tentacules plus grands que le navire lui-même se déployèrent, berçant le Hurle-Tempête et le soustrayant à la fureur des vagues.

En présence du Léviathan, la tempête s'apaisa. Un bourdonnement profond résonna dans l'air, un son qui semblait porter la voix du Vieux Fils. L'équipage, stupéfait, ne put que s'incliner avec respect, car ils savaient qu'ils avaient été jugés dignes de conduire notre peuple aux confins les plus lointains de la terre.</font>]]

Book_Harald_Page3 = [[<font face='Acadian Runes' color='#dbdbdb'>Quand le Léviathan se retira dans les profondeurs, il laissa les Haraldiens dans des eaux calmes, leur navire intact. Par quelque grâce divine, ils se réveillèrent aux quais de la patrie, leur drakkar reposant comme s'il n'avait jamais affronté la tempête. Le Léviathan, dirent-ils, n'était pas seulement l'Ancien Fils manifesté, mais un signe de leur lien avec la mer, une légende qui perdurerait à travers les âges.</font>

<font face='Acadian Runes' color='#dbdbdb' size='4'><b>Une Légende parmi les Clans</b></font>
<font face='Acadian Runes' color='#dbdbdb'>À partir de ce jour, le récit du Léviathan devint une pierre angulaire de l'identité du Clan Harald. Un rappel du pouvoir divin qui veille sur eux et sur les mers qui leur sont chères. L'histoire se répandit parmi les Clans, non pas comme une hérésie mais comme un témoignage du courage des Haraldiens et de leur proximité avec le divin.

Le lien du Clan Harald avec le Léviathan est un héritage qui nous rappelle à tous : les dieux marchent parmi nous, non pas dans des cieux lointains mais au cœur du monde lui-même.</font>]]

Book_Reaver_Page1 = [[<font face='Acadian Runes' color='#dbdbdb' size='4'><b>La Malédiction de la Sœur</b></font>
<font face='Acadian Runes' color='#dbdbdb'>Écoutez le récit du Clan Reaver et de son culte pour la Sœur, notre déesse des ténèbres et de la tromperie. Avec leur maîtrise du commerce, des marchés et des rituels sombres, ils ont forgé le destin. La crainte et le respect s'entremêlent autour des Reavers, car ils sont un Clan aussi brutal que riche. Leurs Loups Rouges taillent leurs ennemis avec une précision impitoyable, ne laissant personne debout sur leur passage. Pourtant, ce n'est pas seulement leur puissance au combat qui les définit.

Les Reavers sont les gardiens de la richesse, les gardiens de la monnaie et du butin. Ce sont eux qui ont négocié le premier accord avec les Nigerii, reliant les terres de l'Est aux nôtres, apportant prospérité et richesses au royaume. Grâce à leur maîtrise de l'esclavage et de la manipulation, ils contrôlaient le flux des marchandises et des informations, méritant ainsi leur rôle d'orateurs de la Sœur. Leur bastion, le Hall des Larmes, se dresse comme un lieu sombre et murmurant parmi les branches, où les âmes sont suspendues dans le tourment entre la vie et la mort, torturées pour le divertissement de leurs geôliers.

La rupture entre le Clan Reaver et le Clan Harald a commencé dans l'orgueil, un orgueil qui s'est rapidement transformé en démesure. Le Clan Harald, audacieux et inflexible après sa rencontre avec le Léviathan - le Vieux Fils fait chair, a conçu un rituel pour naviguer sur le fleuve Styx, le fleuve sacré de la Sœur, croyant que c'était leur droit divin d'explorer les royaumes au-delà. Pour les Haralders, ce fleuve était une épreuve de courage, un symbole de leur lien indestructible avec le Vieux Fils. Mais pour les Reavers, c'était un sacrilège, un affront à leur déesse.</font>]]

Book_Reaver_Page2 = [[<font face='Acadian Runes' color='#dbdbdb' size='4'><b>Le Voyage du Chaland de Feu</b></font>
<font face='Acadian Runes' color='#dbdbdb'>Les Haralders, poussés par leur audace, préparèrent le drakkar <i>Chaland de Feu</i> pour le voyage. Le navire, une grande embarcation construite pour la guerre et l'exploration, était manœuvré par un équipage des marins les plus hardis du clan. Ils partirent au son des chants de bravoure, le cœur empli de confiance, convaincus qu'aucune force ne pourrait les empêcher de s'emparer des secrets du fleuve. Mais le voyage ne se déroula pas comme ils l'avaient imaginé. Le Chaland de Feu navigua de plus en plus profondément dans la lave, franchissant le seuil où la vie et la mort s'entremêlent.

Les jours se firent semaines, et aucune nouvelle ne parvint de l'équipage. Les Haralders, pourtant habitués aux mers, devinrent inquiets, attendant un signe, un retour, quoi que ce soit qui confirme que le Chaland de Feu avait achevé son périple. Mais rien ne vint. Les marins du Chaland de Feu ne revinrent jamais.
Ce n'est qu'après la mystérieuse disparition du drakkar que les rumeurs commencèrent à circuler. Des murmures emplirent l'air, et l'atmosphère s'alourdit d'effroi. Personne ne savait ce qu'était devenu le Chaland de Feu, et personne ne pouvait expliquer l'absence de son équipage. Le voyage sur le fleuve Styx était censé être une affirmation audacieuse de l'esprit inflexible des Haralders, pourtant il s'acheva dans le silence et le mystère.</font>]]

Book_Reaver_Page3 = [[<font face='Acadian Runes' color='#dbdbdb' size='4'><b>La Noyade des Chefs</b></font>
<font face='Acadian Runes' color='#dbdbdb'>Au début, les Haralders cherchèrent à comprendre, pensant peut-être qu'une force naturelle avait réclamé leur navire. Mais au fil du temps, d'autres événements étranges commencèrent à se produire. La mer elle-même semblait s'agiter d'un malaise, et les dirigeants des Haralders, autrefois fiers de se qualifier de "chefs de la mer", commencèrent à rencontrer des morts prématurées et inexplicables. L'un après l'autre, chaque "chef de la mer" se noya dans des circonstances mystérieuses, leurs corps repêchés des flots sans explication. À chaque leader qui périssait, les Haralders commencèrent à soupçonner l'impensable : que le voyage du Bateau-Feu dans le Styx avait réveillé quelque chose de bien plus sombre qu'ils ne pouvaient l'imaginer.

Ainsi, le soupçon commença à s'envenimer. Les Saccageurs, disait-on, niaient toute implication dans la malédiction. Ils affirmaient que c'était la volonté de la Sœur elle-même, que les Haralders avaient osé s'aventurer dans un domaine où les mortels n'avaient pas leur place. Mais alors que les dirigeants des Haralders continuaient de tomber, les murmures s'amplifièrent. Les Saccageurs, disaient certains, devaient être derrière tout cela, que la malédiction était un châtiment pour l'arrogance des Haralders. Mais les Saccageurs eux-mêmes restèrent silencieux, fermes dans leur affirmation que c'était la colère de la Sœur, et non leur main, qui avait réclamé les marins et leur navire.

La vérité, cependant, reste un mystère. Étaient-ce les Saccageurs qui avaient en quelque sorte invoqué la malédiction, ou était-ce la Sœur elle-même, répondant à la défiance des Haralders ? Personne ne le sait avec certitude. Mais ce qui est certain, c'est que la malédiction s'installa, et les Haralders furent laissés brisés, privant notre peuple de la possibilité de voyager sur la mer.</font>]]

Book_Reaver_Page4 = [[<font face='Acadian Runes' color='#dbdbdb' size='4'><b>Une Rivalité Familiale</b></font>
<font face='Acadian Runes' color='#dbdbdb'>Cette révélation brisa la paix fragile entre le Clan Harald et le Clan Reaver. Ce qui n'était autrefois qu'une rivalité commerciale et d'influence devint un conflit amer et sanglant. Les Harald, fiers et furieux, cherchèrent à venger la malédiction. Les Reaver, impénitents et fermes dans leur croyance, considéraient l'action de la Sœur comme justifiée—un châtiment pour l'arrogance du Clan Harald.

Le Fleuve Styx était, après tout, le domaine de la Sœur ; non un don mortel à revendiquer par ceux qui ne l'honoraient pas. Que leur malédiction vienne de la Sœur ou soit l'œuvre du Clan Reaver, elle a projeté des ombres durables sur nous tous.

La rivalité entre le Clan Harald et le Clan Reaver ne prendra jamais fin. Chaque clan voit l'autre comme une menace, un concurrent pour le contrôle des eaux et des richesses qui y circulent. Mais en fin de compte, tous deux sont liés à la même famille. Bien que l'amertume puisse persister entre eux, ils doivent accepter que leurs destins soient à jamais entrelacés.</font>]]